
project_id = "ejyzldnrcgglcnpbxmda"

[functions.mpesa-stk-push]
verify_jwt = false

[functions.mpesa-callback]
verify_jwt = false

[functions.subscription-manager]
verify_jwt = false

[functions.router-control]
verify_jwt = false
